name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: build-output
        path: '**/bin/**'

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
        options: >-
          --health-cmd=" /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 1433:1433
    
    steps:
    - uses: actions/checkout@v4
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4.3.0
      with:
        name: build-output

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Run Tests
      env:
        ConnectionStrings__Default: "Server=localhost,1433;Database=master;User Id=sa;Password=YourStrong!Passw0rd;"
      run: dotnet test --no-build --verbosity normal
