name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  ARTIFACTS: ./build_artifacts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Create Artifacts
        run: |
          UNIT_TESTS="${ARTIFACTS}/UnitTests"
          INTEGRATION_TESTS="${ARTIFACTS}/IntegrationTests"
          mkdir -p "$UNIT_TESTS"
          mkdir -p "$INTEGRATION_TESTS"
          cp -r src/UnitTests/bin/Debug/net8.0/* "$UNIT_TESTS"/
          cp -r src/IntegrationTests/bin/Debug/net8.0/* "$INTEGRATION_TESTS"/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: ${{ env.ARTIFACTS }}
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
        ConnectionStrings__Default: Host=localhost;Port=5432;Database=testdb;Username=testuser;Password=testPassword
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testPassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Download build artifacts
        uses: actions/download-artifact@v4.3.0
        with: 
          name: build_artifacts
          path: ${{ env.ARTIFACTS }}
      - name: Test
        run: dotnet test ${{ env.ARTIFACTS }} --no-build --verbosity normal
